language: java
jdk: openjdk7
notifications:
  email: false
  slack:
    secure: DVv/YhOeWNj13mGjJJGyVXrgDLY9h7Md0DDwFSQo63NhQ3ygua29r4uUnNczpSUUtEoxma6jLofiaArVdJfXzKNXjdr9XNq6WC40yA6ksKvLTwkI2EAY4VoaRdyrk+8AddbKQai+IdDkWhUuhXAckICGDp6lHS/omcWeJeFDgcI=
env:
  global: TERM=dumb
before_install:
  - echo "libs_path=." > gradle.properties
install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S
after_success: ./gradlew curse -S
